export enum AccountStackNavigatorEnum {
    AddConversationPeopleScreen = 'AddConversationPeopleScreen',
    AddHangoutInvitationsScreen = 'AddHangoutInvitationsScreen',
    ProfileScreen = 'ProfileScreen',
    PeopleScreen = 'PeopleScreen',
    PersonAccountScreen = 'PersonAccountScreen',
    CreateGroupHangoutScreen = 'CreateGroupHangoutScreen',
    PickPeopleScreen = 'PickPeopleScreen',
    HangoutsScreen = 'HangoutsScreen',
    NotificationsScreen = 'NotificationsScreen',
    MessagesScreen = 'MessagesScreen',
    ChatScreen = 'ChatScreen',
    ChatDetailScreen = 'ChatDetailScreen',
    PictureScreen = 'PictureScreen',
    EventScreen = 'EventScreen',
    HangoutDetailScreen = 'HangoutDetailScreen',
    AccountScreen = 'AccountScreen',
    ChangePasswordScreen = 'ChangePasswordScreen',
    DeleteAccountScreen = 'DeleteAccountScreen',
    SelectGroupHangoutUsersScreen = 'SelectGroupHangoutUsersScreen'
}
